all:
	javac swapper/Swapper.java -Xlint:unchecked
	javac validate/Validate.java -Xlint:unchecked
	javac producerConsumer/ProducerConsumer.java -Xlint:unchecked
	javac readerWriter/ReaderWriter.java -Xlint:unchecked
